version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      routine-rust-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      vite:
        patterns:
          - vite
          - "@vitejs/*"
      routine-npm-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
