[package]
name = "emumi"
version = "0.2.8"
edition = "2024"
description = "A friendly Android emulator manager for Linux"
license = "MIT"
repository = "https://github.com/elroykanye/emumi"
homepage = "https://github.com/elroykanye/emumi"
readme = "README.md"
keywords = ["android", "emulator", "linux", "avd", "tauri"]
categories = ["development-tools", "gui"]
build = "build.rs"

[dependencies]
axum = "0.8.9"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net", "time"] }
tauri = { version = "2.8.5", default-features = false, features = ["wry", "x11"] }

[build-dependencies]
png = "0.18.1"
tauri-build = { version = "2.4.1", features = [] }
